<?php
// export_pdf.php
session_start();
if (!isset($_SESSION['username'])) {
    header('Location: Login.php');
    exit;
}

require_once 'vendor/autoload.php'; // Sesuaikan path
use Dompdf\Dompdf;
use Dompdf\Options;

include 'koneksi.php';

$type = $_GET['type'] ?? 'users'; // 'users' atau 'tiket'
$title = '';

// Query berdasarkan tipe
if ($type === 'users') {
    $sql = "SELECT * FROM tb_pembeli ORDER BY id_pembeli DESC";
    $result = mysqli_query($koneksi, $sql);
    $data = mysqli_fetch_all($result, MYSQLI_ASSOC);
    $title = "DATA REGISTRASI PENGGUNA";
    $columns = ['ID', 'Nama', 'Username', 'Email', 'Alamat', 'Jenis Kelamin', 'Tanggal Lahir', 'Bergabung'];
} else if ($type === 'tiket') {
    $sql = "SELECT * FROM tb_tiket ORDER BY id_tiket DESC";
    $result = mysqli_query($koneksi, $sql);
    $data = mysqli_fetch_all($result, MYSQLI_ASSOC);
    $title = "DATA PEMBELIAN TIKET";
    $columns = ['ID', 'Judul Tiket', 'Jumlah', 'Harga Satuan', 'Total Harga', 'Metode Pembayaran', 'Status Pembayaran'];
}

// Buat HTML untuk PDF
$html = '
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>' . $title . '</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { color: #333; text-align: center; margin-bottom: 20px; }
        .info { text-align: center; margin-bottom: 30px; color: #666; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #4caf50; color: white; padding: 10px; text-align: left; }
        td { padding: 8px; border-bottom: 1px solid #ddd; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .footer { text-align: center; margin-top: 50px; color: #777; font-size: 12px; }
        .page-number:after { content: counter(page); }
    </style>
</head>
<body>
    <h1>' . $title . '</h1>
    <div class="info">
        <p>Dibuat oleh: ' . htmlspecialchars($_SESSION['username']) . '</p>
        <p>Tanggal: ' . date('d-m-Y H:i:s') . '</p>
        <p>Total Data: ' . count($data) . '</p>
    </div>
    <table>
        <thead>
            <tr>';

// Header kolom
foreach ($columns as $col) {
    $html .= '<th>' . $col . '</th>';
}

$html .= '</tr>
        </thead>
        <tbody>';

// Data rows
if (!empty($data)) {
    foreach ($data as $row) {
        $html .= '<tr>';
        if ($type === 'users') {
            $html .= '
                <td>' . $row['id_pembeli'] . '</td>
                <td>' . htmlspecialchars($row['nama_pembeli']) . '</td>
                <td>' . htmlspecialchars($row['username']) . '</td>
                <td>' . htmlspecialchars($row['email']) . '</td>
                <td>' . htmlspecialchars($row['alamat']) . '</td>
                <td>' . htmlspecialchars($row['jenis_kelamin']) . '</td>
                <td>' . htmlspecialchars($row['tanggal_lahir']) . '</td>
                <td>' . htmlspecialchars($row['create_at']) . '</td>';
        } else if ($type === 'tiket') {
            $html .= '
                <td>' . $row['id_tiket'] . '</td>
                <td>' . htmlspecialchars($row['judul_tiket']) . '</td>
                <td>' . $row['jumlah_tiket'] . '</td>
                <td>Rp ' . number_format($row['harga_satuan'], 0, ',', '.') . '</td>
                <td>Rp ' . number_format($row['total_harga'], 0, ',', '.') . '</td>
                <td>' . htmlspecialchars($row['metode_pembayaran']) . '</td>
                <td>' . htmlspecialchars($row['status_pembayaran']) . '</td>';
        }
        $html .= '</tr>';
    }
} else {
    $html .= '<tr><td colspan="' . count($columns) . '" style="text-align: center;">Tidak ada data</td></tr>';
}

$html .= '
        </tbody>
    </table>
    <div class="footer">
        <p>Halaman <span class="page-number"></span></p>
        <p>© ' . date('Y') . ' Admin Panel - Generated by Dompdf</p>
    </div>
</body>
</html>';

// Konfigurasi Dompdf
$options = new Options();
$options->set('isHtml5ParserEnabled', true);
$options->set('isRemoteEnabled', true);
$options->set('defaultFont', 'Arial');

$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape'); // Landscape untuk tabel lebar
$dompdf->render();

// Output PDF
$dompdf->stream($title . '_' . date('Ymd_His') . '.pdf', [
    'Attachment' => true // true untuk download otomatis
]);
?>